import * as fs from "fs";

export let byKeyword = {
  pinkrabbit: {
    name: "pinkrabbit",
    list_keywords: [
      "soflens pinkrabbit",
      "softlens",
      "soflens eyesm",
      "softlens kawaigankyu",
      "softlens eyeslandcon",
      "soflens kittykawai",
      "softlens naturalens",
      "softlens eyeloven",
      "softlens eyesightlenses",
      "softlens ras eye",
      "softlens bening",
      "softlens warna",
      "softlens minus",
      "lensa kontak",
      "lensa kontak universal",
      "lensa kontak minus",
      "eye drops softlens",
      "eyedrops softlens",
      "eyedrop softlens",
      "tetes mata softlens",
      "cairan softlens",
      "lenscase",
      "softlens case",
      "lensa kontak case",
    ],
  },
  quotidien_salad: {
    name: "quotidien_salad",
    list_keywords: [
      "Makanan Sehat",
      "Makanan Sehat Diet",
      "Makanan Diet",
      "Makanan Sehat Instan",
      "Makanan Sehat Rendah Kalori",
      "Healthy Food",
      "Healthy Snack",
      "Healthy Food Diet",
      "Diet Food",
      "Snack sehat diet",
      "Snack sehat gluten free",
      "Minuman Sehat",
      "Minuman Diet",
      "Minuman Rendah Kalori",
    ],
  },
};

export let byCategory = {
  pinkrabbit: {
    name: "pinkrabbit",
    cat: "cat3",
    lis_category: [
      "Softlens",
      "Tetes Mata Softlens",
      "Cairan Pembersih Softlens",
    ],
  },
  quotidien_salad: {
    name: "quotidien_salad",
    cat: "cat3",
    lis_category: [
      "Biskuit & Wafer",
      "Camilan Instant",
      "Kue Kering",
      "Ready to Eat (Siap Makan)",
      "Sereal",
      "Mie Impor",
      "Aneka Pasta",
      "Mie Instan",
      "Madu",
      "Minuman Tradisional",
      "Obat Herbal",
      "Vitamin & Nutrisi",
      "Keripik",
      "Kue Basah",
      "Makanan Ringan Lainnya",
      "Mie Telur",
      "Bihun & Soun",
      "Kacang",
      "Kerupuk",
    ],
  },
  perawatandankecantikan: {
    name: "perawatandankecantikan",
    cat: "cat1",
    lis_category: ["Kecantikan"],
  },
};
